### PR TITLE
dockerize: build a fully functional tracking_services within a docker

### LINKED ISSUE #10: Dockerize Tracking Service
**Is your feature request related to a problem? Please describe.**
See current docker installation. Let's update the installation to use Docker to spin up the service.

### PR DESCRIPTION
**Pull request by al-niessner**
Closes #10

### CODE REVIEW

**Comment by al-niessner** [comment]
Works both local and release. Tested the release with a release in a different repo.

Need to update 0.5.0 release to note it as not docker friendly.

**Comment by al-niessner** [comment]
@jordanpadams 
Reviewers are being weird as I cannot add you. Please look it over though.

**Comment by jordanpadams** [comment]
@al-niessner thanks. will try to take a look. may be a couple days. let's chat at the  breakout this afternoon about the next ticket: https://github.com/NASA-PDS/tracking-service/issues/11

**Review by tloubrieu-jpl — COMMENTED** [review]
Hi @al-niessner ,

I've been able to build and run the docker image on my laptop.
Note on macos I used following command to run instead of the one in documentation:

docker run --rm -p 8080:8080 <container>

(with --network=host I was not able to reach the server, it said localhost:8080 not available) 

Thanks, that is good.

Then I wanted to test the API but I can not find a working url. I tried:

http://localhost:8080/json/users or http://localhost:8080/tracking/json/users

Do you know which url can be requested ?

**Comment by al-niessner** [comment]
In response to:

> Do you know which url can be requested?

I do not. This has been my question about how do I test it. When I run `docker run --rm --expose 8080:8080 tracking_service:$(git rev-parse HEAD)` I see that tomcat is up and running. I have copied the WAR to the tomcat webapps directory. From there, I know nothing else like what URL tracking services responds to and most importantly the expected response. If I had that information I could finish testing and then answer your question.

**Pull request merged**
